//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPHPWebService.MyPhpSoapServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:myTns", ConfigurationName="MyPhpSoapServer.MyPortType")]
    public interface MyPortType {
        
        // CODEGEN: Generating message contract since the operation SumData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MyPHPWebService.MyPhpSoapServer.SumDataResponse SumData(MyPHPWebService.MyPhpSoapServer.SumDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.SumDataResponse> SumDataAsync(MyPHPWebService.MyPhpSoapServer.SumDataRequest request);
        
        // CODEGEN: Generating message contract since the operation SubData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MyPHPWebService.MyPhpSoapServer.SubDataResponse SubData(MyPHPWebService.MyPhpSoapServer.SubDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.SubDataResponse> SubDataAsync(MyPHPWebService.MyPhpSoapServer.SubDataRequest request);
        
        // CODEGEN: Generating message contract since the operation MulData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MyPHPWebService.MyPhpSoapServer.MulDataResponse MulData(MyPHPWebService.MyPhpSoapServer.MulDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.MulDataResponse> MulDataAsync(MyPHPWebService.MyPhpSoapServer.MulDataRequest request);
        
        // CODEGEN: Generating message contract since the operation DivData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MyPHPWebService.MyPhpSoapServer.DivDataResponse DivData(MyPHPWebService.MyPhpSoapServer.DivDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.DivDataResponse> DivDataAsync(MyPHPWebService.MyPhpSoapServer.DivDataRequest request);
        
        // CODEGEN: Generating message contract since the operation hello is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MyPHPWebService.MyPhpSoapServer.helloResponse hello(MyPHPWebService.MyPhpSoapServer.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.helloResponse> helloAsync(MyPHPWebService.MyPhpSoapServer.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int sumnum1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int sumnum2;
        
        public SumDataRequest() {
        }
        
        public SumDataRequest(int sumnum1, int sumnum2) {
            this.sumnum1 = sumnum1;
            this.sumnum2 = sumnum2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string anssum;
        
        public SumDataResponse() {
        }
        
        public SumDataResponse(string anssum) {
            this.anssum = anssum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int subnum1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int subnum2;
        
        public SubDataRequest() {
        }
        
        public SubDataRequest(int subnum1, int subnum2) {
            this.subnum1 = subnum1;
            this.subnum2 = subnum2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string anssub;
        
        public SubDataResponse() {
        }
        
        public SubDataResponse(string anssub) {
            this.anssub = anssub;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MulDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int mulnum1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int mulnum2;
        
        public MulDataRequest() {
        }
        
        public MulDataRequest(int mulnum1, int mulnum2) {
            this.mulnum1 = mulnum1;
            this.mulnum2 = mulnum2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MulDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ansmul;
        
        public MulDataResponse() {
        }
        
        public MulDataResponse(string ansmul) {
            this.ansmul = ansmul;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int divnum1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int divnum2;
        
        public DivDataRequest() {
        }
        
        public DivDataRequest(int divnum1, int divnum2) {
            this.divnum1 = divnum1;
            this.divnum2 = divnum2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ansdiv;
        
        public DivDataResponse() {
        }
        
        public DivDataResponse(string ansdiv) {
            this.ansdiv = ansdiv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string response;
        
        public helloResponse() {
        }
        
        public helloResponse(string response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyPortTypeChannel : MyPHPWebService.MyPhpSoapServer.MyPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyPortTypeClient : System.ServiceModel.ClientBase<MyPHPWebService.MyPhpSoapServer.MyPortType>, MyPHPWebService.MyPhpSoapServer.MyPortType {
        
        public MyPortTypeClient() {
        }
        
        public MyPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPHPWebService.MyPhpSoapServer.SumDataResponse MyPHPWebService.MyPhpSoapServer.MyPortType.SumData(MyPHPWebService.MyPhpSoapServer.SumDataRequest request) {
            return base.Channel.SumData(request);
        }
        
        public string SumData(int sumnum1, int sumnum2) {
            MyPHPWebService.MyPhpSoapServer.SumDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.SumDataRequest();
            inValue.sumnum1 = sumnum1;
            inValue.sumnum2 = sumnum2;
            MyPHPWebService.MyPhpSoapServer.SumDataResponse retVal = ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).SumData(inValue);
            return retVal.anssum;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.SumDataResponse> MyPHPWebService.MyPhpSoapServer.MyPortType.SumDataAsync(MyPHPWebService.MyPhpSoapServer.SumDataRequest request) {
            return base.Channel.SumDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.SumDataResponse> SumDataAsync(int sumnum1, int sumnum2) {
            MyPHPWebService.MyPhpSoapServer.SumDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.SumDataRequest();
            inValue.sumnum1 = sumnum1;
            inValue.sumnum2 = sumnum2;
            return ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).SumDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPHPWebService.MyPhpSoapServer.SubDataResponse MyPHPWebService.MyPhpSoapServer.MyPortType.SubData(MyPHPWebService.MyPhpSoapServer.SubDataRequest request) {
            return base.Channel.SubData(request);
        }
        
        public string SubData(int subnum1, int subnum2) {
            MyPHPWebService.MyPhpSoapServer.SubDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.SubDataRequest();
            inValue.subnum1 = subnum1;
            inValue.subnum2 = subnum2;
            MyPHPWebService.MyPhpSoapServer.SubDataResponse retVal = ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).SubData(inValue);
            return retVal.anssub;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.SubDataResponse> MyPHPWebService.MyPhpSoapServer.MyPortType.SubDataAsync(MyPHPWebService.MyPhpSoapServer.SubDataRequest request) {
            return base.Channel.SubDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.SubDataResponse> SubDataAsync(int subnum1, int subnum2) {
            MyPHPWebService.MyPhpSoapServer.SubDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.SubDataRequest();
            inValue.subnum1 = subnum1;
            inValue.subnum2 = subnum2;
            return ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).SubDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPHPWebService.MyPhpSoapServer.MulDataResponse MyPHPWebService.MyPhpSoapServer.MyPortType.MulData(MyPHPWebService.MyPhpSoapServer.MulDataRequest request) {
            return base.Channel.MulData(request);
        }
        
        public string MulData(int mulnum1, int mulnum2) {
            MyPHPWebService.MyPhpSoapServer.MulDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.MulDataRequest();
            inValue.mulnum1 = mulnum1;
            inValue.mulnum2 = mulnum2;
            MyPHPWebService.MyPhpSoapServer.MulDataResponse retVal = ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).MulData(inValue);
            return retVal.ansmul;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.MulDataResponse> MyPHPWebService.MyPhpSoapServer.MyPortType.MulDataAsync(MyPHPWebService.MyPhpSoapServer.MulDataRequest request) {
            return base.Channel.MulDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.MulDataResponse> MulDataAsync(int mulnum1, int mulnum2) {
            MyPHPWebService.MyPhpSoapServer.MulDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.MulDataRequest();
            inValue.mulnum1 = mulnum1;
            inValue.mulnum2 = mulnum2;
            return ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).MulDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPHPWebService.MyPhpSoapServer.DivDataResponse MyPHPWebService.MyPhpSoapServer.MyPortType.DivData(MyPHPWebService.MyPhpSoapServer.DivDataRequest request) {
            return base.Channel.DivData(request);
        }
        
        public string DivData(int divnum1, int divnum2) {
            MyPHPWebService.MyPhpSoapServer.DivDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.DivDataRequest();
            inValue.divnum1 = divnum1;
            inValue.divnum2 = divnum2;
            MyPHPWebService.MyPhpSoapServer.DivDataResponse retVal = ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).DivData(inValue);
            return retVal.ansdiv;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.DivDataResponse> MyPHPWebService.MyPhpSoapServer.MyPortType.DivDataAsync(MyPHPWebService.MyPhpSoapServer.DivDataRequest request) {
            return base.Channel.DivDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.DivDataResponse> DivDataAsync(int divnum1, int divnum2) {
            MyPHPWebService.MyPhpSoapServer.DivDataRequest inValue = new MyPHPWebService.MyPhpSoapServer.DivDataRequest();
            inValue.divnum1 = divnum1;
            inValue.divnum2 = divnum2;
            return ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).DivDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPHPWebService.MyPhpSoapServer.helloResponse MyPHPWebService.MyPhpSoapServer.MyPortType.hello(MyPHPWebService.MyPhpSoapServer.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            MyPHPWebService.MyPhpSoapServer.helloRequest inValue = new MyPHPWebService.MyPhpSoapServer.helloRequest();
            inValue.name = name;
            MyPHPWebService.MyPhpSoapServer.helloResponse retVal = ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).hello(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.helloResponse> MyPHPWebService.MyPhpSoapServer.MyPortType.helloAsync(MyPHPWebService.MyPhpSoapServer.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPHPWebService.MyPhpSoapServer.helloResponse> helloAsync(string name) {
            MyPHPWebService.MyPhpSoapServer.helloRequest inValue = new MyPHPWebService.MyPhpSoapServer.helloRequest();
            inValue.name = name;
            return ((MyPHPWebService.MyPhpSoapServer.MyPortType)(this)).helloAsync(inValue);
        }
    }
}
